### ISSUE TITLE
Not working correctly on theme server

### ISSUE THREAD

**Issue by thomasdavis** [jalooc/jsonresume-theme-smart#1]
http://themes.jsonresume.org/theme/smart

It looks like nunjucks is in the dependency list so I can't figure out why it didn't install.

**Comment by jalooc** [comment]
Me neither _(yet)_. This literally worked yesterday and today it doesn't in spite of changing completely nothing. I also checked the `render` function exported from `index.js` and the function generates html correctly. Gulp task fired by running `npm run dev` imports and uses it directly, so it was easy to inspect. I'm not sure, but it looks like some problem with [theme server](https://github.com/jsonresume/theme-manager). I'll try to dig around it when I have time.

**Comment by thomasdavis** [comment]
Ahh just went on theme server to suss things out.... no disk space =D, fixing now.

**Comment by jalooc** [comment]
Great, thanks :) Closing then.

**Comment by thomasdavis** [comment]
Well getting this error now -> http://themes.jsonresume.org/theme/smart

I think that is due to a relative parsing issue, might need to use `__dirname` somewhere

**Comment by jalooc** [comment]
Ok, up 'n' running
